version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: navigating1
      POSTGRES_DB: control
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"